projekt/urls.py
"""
    urls
"""
from django.contrib import admin
from django.urls import path

from app.views.users_view import register_page, create_admin, login_page, logout_user, home
from app.views.round_view import generate_next_round
from app.views.arenas_view import enter_result
from app.views.players_view import\
    delete_players,\
    update_player,\
    create_player,\
    my_players_list,\
    all_players_list
from app.views.tournaments_view import\
    create_tournament,\
    update_tournament,\
    tournaments_list,\
    all_tournaments_in_progress,\
    filtered_all_tournaments_in_progress,\
    filtered_tournaments_list,\
    tournaments_detail,\
    start_tournament,\
    delete_tournaments,\
    finish_tournaments

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register_page, name='register'),
    path('create_admin/', create_admin, name='create_admin'),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    path('', home, name='home'),

    path('players/list/', my_players_list, name='my_players_list'),
    path('players/list/all/', all_players_list, name='all_players_list'),
    path('players/update/<int:pk>/', update_player, name="update_players"),
    path('players/add', create_player, name="create_players"),
    path('players/<int:pk>/delete/', delete_players, name="delete_players"),

    path('tournaments/add', create_tournament, name="create_tournaments"),
    path('tournaments/update/<int:pk>/', update_tournament, name="update_tournaments"),
    path('tournaments/list/<str:value>/', tournaments_list, name="tournaments_list"),
    path('tournaments/list_all_in_progress/',
         all_tournaments_in_progress,
         name="all_tournaments_in_progress"
         ),
    path('tournaments/filtred_list_all_in_progress/',
         filtered_all_tournaments_in_progress,
         name="filtered_all_tournaments_in_progress"
         ),
    path('tournaments/list/filtered/<str:value>',
         filtered_tournaments_list,
         name="filtered_tournaments_list"
         ),
    path('tournaments/detail/<slug:pk>/', tournaments_detail, name="tournaments_detail"),
    path('tournaments/start/<slug:pk>/', start_tournament, name="start_tournament"),
    path('tournaments/<int:pk>/delete/', delete_tournaments, name="delete_tournaments"),
    path('tournaments/<int:pk>/finish/', finish_tournaments, name="finish_tournaments"),

    path('rounds/generate_next/<int:pk>/', generate_next_round, name="generate_next_round"),

    path('arenas/set_result/<int:pk>/', enter_result, name="enter_result"),
]

app/models/arena_model.py
from django.db import models
from app.models.player_model import Player
from app.models.round_model import Round


class Arena(models.Model):
    round = models.ForeignKey(Round, null=True, on_delete=models.CASCADE)
    player1 = models.ForeignKey(Player, related_name='player1',  on_delete=models.CASCADE)
    player2 = models.ForeignKey(Player, related_name='player2', on_delete=models.CASCADE)
    arena_number = models.IntegerField('Stolik nr', null=True)

    def __str__(self):
        return self.round.tournament.name \
               + ' - runda_' + str(self.round.round_number) \
               + ' - stolik_' + str(self.arena_number)

app/models/result_model.py
from django.db import models
from app.models.player_model import Player
from app.models.arena_model import Arena


class Result(models.Model):
    arena = models.ForeignKey(Arena, null=True, on_delete=models.CASCADE)
    winner = models.ForeignKey(Player, on_delete=models.CASCADE)

    def __str__(self):
        return 'zwyciezyl ' + self.winner.name

app/models/round_model.py
from django.db import models
from app.models.tournament_model import Tournament


class Round(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    round_number = models.IntegerField('Runda nr',null=True)

    def __str__(self):
        return self.tournament.name + ' - runda_' + str(self.round_number)

app/forms/tournaments_form.py
from django import forms
from app.models import Tournament, Player


class CreateTournamentForm(forms.ModelForm):

    class Meta:
        model = Tournament
        fields = '__all__'
        exclude = ['is_started', 'is_finished', 'user']

        widgets = {
            'start_date': forms.DateInput(
                format='%d-%m-%Y',
                attrs={'class': 'form-control',
                       'type': 'date'
                       }),
            'players': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, user, *args, **kwargs):
        super(CreateTournamentForm, self).__init__(*args, **kwargs)
        self.fields['players'].queryset = Player.objects.exclude(name="WALKOWER").filter(user=user)


class UpdateTournamentForm(forms.ModelForm):
    class Meta:
        model = Tournament
        fields = '__all__'
        exclude = ['is_started', 'is_finished', 'user']

        widgets = {
            'start_date': forms.DateInput(
                format='%Y-%m-%d',
                attrs={'class': 'form-control',
                       'type': 'date'
                       }),
            'players': forms.CheckboxSelectMultiple(),
        }

app/views/tournaments_view.py
from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from app.decorators import allowed_users
from app.models import Tournament, Round, Arena, Player, Result
from app.forms.tournaments_form import CreateTournamentForm, UpdateTournamentForm
import numpy as np
from django.contrib import messages


@allowed_users(allowed_roles=['user', 'admin'])
def delete_tournaments(request, pk):
    model = Tournament.objects.filter(pk=pk)
    if model.filter(user=request.user).first() or request.user.is_superuser:
        if request.method == 'POST':
            if model.filter(is_started=False, is_finished=False).first() or request.user.is_superuser:
                model.delete()
                messages.success(request, 'Pomyślnie usunięto turniej')
            else:
                messages.error(request, 'Turniej można usunąć jedynie przed jego rozpoczęciem')
    else:
        messages.error(request, 'Próba usunięcia turnieju innego użytkownika')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class RoundsStatusHelper:
    round_number = 0
    finished_table = 0
    total_table = 0


def count_finished_arenas_on_round(pk):
    my_list = []
    for round_ in Round.objects.filter(tournament=pk):
        arenas = list(Arena.objects.filter(round=round_.pk))
        arenas_finished = 0
        for arena in arenas:
            results = list(Result.objects.filter(arena=arena))
            for result in results:
                if result.winner:
                    arenas_finished = arenas_finished + 1
        x = RoundsStatusHelper()
        x.round_number = round_.round_number
        x.finished_table = arenas_finished
        x.total_table = len(arenas)
        my_list.append(x)
    return my_list


def tournaments_detail(request, pk):
    if request.user.is_anonymous:
        model = Tournament.objects.filter(pk=pk)
        if model.filter(is_started=True, is_finished=False):
            context = {'tournament': model.first(), 'rounds_status': count_finished_arenas_on_round(pk)}
            return render(request, 'app/tournaments/detail.html', context)
        else:
            messages.error(request, "Użytkownik anonimowy może przeglądać jedynie trwające turnieje")
            return redirect('home')
    else:
        model = Tournament.objects.filter(pk=pk)
        context = {'tournament': model.first(), 'rounds_status': count_finished_arenas_on_round(pk)}
        return render(request, 'app/tournaments/detail.html', context)


@allowed_users(allowed_roles=['user', 'admin'])
def update_tournament(request, pk):
    model = Tournament.objects.filter(pk=pk)
    if model.filter(user=request.user).first() or request.user.is_superuser:
        if model.filter(is_started=False, is_finished=False).first() or request.user.is_superuser:
            instance = model.first()
            form = CreateTournamentForm(user=request.user, instance=instance)
            if request.method == 'POST':
                form = UpdateTournamentForm(request.POST)
                if form.is_valid():
                    model.filter(pk=pk).update(name=str(request.POST['name']))
                    model.filter(pk=pk).update(max_players=int(request.POST['max_players']))
                    model.filter(pk=pk).update(
                        start_date=datetime.strptime(request.POST['start_date'], '%Y-%m-%d')
                    )
                    model.filter(pk=pk).first().players.clear()

                    selected_players = list(form.cleaned_data.get('players'))
                    for player in selected_players:
                        model.filter(pk=pk).first().players.add(player.id)
                    messages.success(request, 'Turniej ' + str(request.POST['name']) + ' edytowany pomyślnie.')
                    return redirect('tournaments_list', 'planned')
                else:
                    messages.error(request, 'Do turnieju musi być przypisany co najmniej jeden gracz.')
            context = {'form': CreateTournamentForm(user=request.user, instance=instance)}
            return render(request, 'app/tournaments/update.html', context)
        else:
            messages.error(request, 'Turniej można edytować jedynie przed jego rozpoczęciem')
    else:
        messages.error(request, 'Próba edycji turnieju innego użytkownika')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@allowed_users(allowed_roles=['user', 'admin'])
def create_tournament(request):
    form = CreateTournamentForm(user=request.user)

    walkower = Player.objects.filter(user=request.user, name='WALKOWER').first()
    if not walkower:
        p = Player()
        p.user = request.user
        p.name = "WALKOWER"
        p.save()

    if request.method == 'POST':
        form = CreateTournamentForm(request.user, request.POST)
        if form.is_valid():
            tournament_name_used = Tournament.objects.filter(
                user=request.user,
                name=request.POST['name']
            ).first()
            if not tournament_name_used:
                selected_players = list(form.cleaned_data.get('players'))
                if int(request.POST['max_players']) >= len(selected_players):
                    tournament = form.save(commit=False)
                    tournament.user = request.user
                    tournament.is_started = False
                    tournament.is_finished = False
                    tournament.save()

                    for player in selected_players:
                        tournament.players.add(player.id)
                    tournament.save()

                    messages.success(request, 'Turniej ' + tournament.name + ' utworzony pomyślnie')

                    return redirect('tournaments_list', 'planned')
                else:
                    messages.error(
                        request,
                        'Próbowano przypisać zbyt wielu Graczy (ustawiono limit ' +
                        str(request.POST['max_players']) + ' uczestników).'
                    )
            else:
                messages.error(request, 'Turniej o nazwie \"' + request.POST['name'] + '\" już istnieje.')
        else:
            messages.error(
                request,
                'Maksymalna liczba graczy musi być większa niż 2 oraz musi być minimum 1 przypisany gracz.'
            )

    context = {'form': form}
    return render(request, 'app/tournaments/add.html', context)


def all_tournaments_in_progress(request):
    title = "Wszystkie trawjące turnieje"
    tournaments = Tournament.objects.filter(
        is_started=True,
        is_finished=False
    )
    context = {'tournaments': tournaments, 'title': title}
    return render(request, 'app/tournaments/list.html', context)


def filtered_all_tournaments_in_progress(request):
    date_from = str(request.POST['date_from'])
    date_to = str(request.POST['date_to'])
    title = "Wszystkie trawjące turnieje"
    tournaments = Tournament.objects.filter(
        is_started=True,
        is_finished=False,
        start_date__gte=date_from,
        start_date__lte=date_to
    )
    context = {
        'tournaments': tournaments,
        'title': title,
        'period_time': date_from + ' - ' + date_to
    }
    return render(request, 'app/tournaments/list.html', context)


@allowed_users(allowed_roles=['user', 'admin'])
def tournaments_list(request, value):
    if value == 'all':
        if request.user.is_superuser:
            tournaments = Tournament.objects.all()
            title = "Wszystkie turnieje"
        else:
            messages.error(request, 'Nie jesteś administatorem')
            return redirect('home')
    elif value == 'planned':
        tournaments = Tournament.objects.filter(
            user=request.user,
            is_started=False,
            is_finished=False
        )
        title = "Turnieje zaplanowane"
    elif value == 'in_progress':
        tournaments = Tournament.objects.filter(
            user=request.user,
            is_started=True,
            is_finished=False
        )
        title = "Turnieje w trakcie"
    else:
        title = "Turnieje zakończone"
        tournaments = Tournament.objects.filter(
            user=request.user,
            is_started=False,
            is_finished=True
        )
    context = {'tournaments': tournaments, 'title': title}
    return render(request, 'app/tournaments/list.html', context)


@allowed_users(allowed_roles=['user', 'admin'])
def filtered_tournaments_list(request, value):
    date_from = str(request.POST['date_from'])
    date_to = str(request.POST['date_to'])
    if value == 'all':
        if request.user.is_superuser:
            tournaments = Tournament.objects.filter(
                start_date__gte=date_from,
                start_date__lte=date_to
            )
            title = "Wszystkie turnieje"
        else:
            messages.error(request, 'Nie jesteś administatorem')
            return redirect('home')
    elif value == 'planned':
        tournaments = Tournament.objects.filter(
            user=request.user,
            is_started=False,
            is_finished=False,
            start_date__gte=date_from,
            start_date__lte=date_to
        )
        title = "Turnieje zaplanowane"
    elif value == 'in_progress':
        tournaments = Tournament.objects.filter(
            user=request.user,
            is_started=True,
            is_finished=False,
            start_date__gte=date_from,
            start_date__lte=date_to
        )
        title = "Turnieje w trakcie"
    else:
        title = "Turnieje zakończone"
        tournaments = Tournament.objects.filter(
            user=request.user,
            is_started=False,
            is_finished=True,
            start_date__gte=date_from,
            start_date__lte=date_to
        )
    context = {
        'tournaments': tournaments,
        'title': title,

templates/app/tournaments/add.html
{% extends 'app/scheleton.html' %}

{% block content %}
    <div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="main-card mt-5">
				<div class="d-flex justify-content-center">
					<h3 id="form-title" class="mt-2">Dodaj turniej</h3>
				</div>
				<div class="d-flex justify-content-center form_container mb-4">
					<form method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-6">
                                {{ form.name.label_tag }}
                                <div class="input-group mb-3">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-trophy"></i></span>
                                    </div>
                                    {{ form.name }}
                                </div>
                                {{ form.start_date.label_tag }}
                                <div class="input-group mb-3">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                                    </div>
                                    {{ form.start_date }}
                                </div>
                                {{ form.max_players.label_tag }}
                                <div class="input-group mb-3">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-users"></i></span>
                                    </div>
                                    {{ form.max_players }}
                                </div>
                            </div>
                            <div class="col-6">
                                <label>Przypisz graczy:</label>
                                <ul class="list-group" id="player-list">
                                    {% for p in form.players  %}
                                            <li class="list-group-item list-background">{{ p }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="d-flex justify-content-center mt-4 login_container">
                            <input class="btn login_btn" type="submit" value="Dodaj turniej">
                        </div>
					</form>
				</div>
			</div>
		</div>
	</div>

    <script>
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder='Nazwa';
        form_fields[3].placeholder='Max graczy';


        for (var field in form_fields){
            form_fields[field].className += ' form-control'
        }
	</script>

{% endblock %}

templates/app/tournaments/detail.html
{% extends 'app/scheleton.html' %}

{% block content %}
{% load poll_extras %}

<div class="mt-4">
    <div class="container w-25 float-left max-w-250 mt-2">
        <h4>Lista startowa</h4>
        <ul class="list-group">
            {% for player in tournament.players.all  %}
                <li class="list-group-item list-background">{{ forloop.counter }}. {{ player.name }}</li>
            {% endfor %}
        </ul>
    </div>
    <div class="container w-75 float-left">
        <div class="row">
            <div class="col-sm-8"><h3 class="display-4">Turniej: <b>{{ tournament }}</b></h3></div>
            <div class="col-sm-4">
                Organizator: <b>{{ tournament.user }}</b><br>
                Data rozpoczęcia <b>{{ tournament.start_date.date }}</b>
            </div>
        </div>
        <div class="dashboard">
            <div class="container h-100">
                <div class="row">
                    {% for round in tournament.round_set.all  %}
                        <div class="col border">
                          <p class="round-title font-weight-bold">Runda {{ round.round_number }}</p>
                        <div class="row">
                            {% for x in rounds_status %}
                                {% if x.round_number == round.round_number and not tournament.is_finished %}
                                    {% if x.finished_table  == x.total_table and x.total_table != 0 and x.round_number != tournament.round_set.count%}
                                        {% with next_e=tournament.round_set.all|next:forloop.counter0 %}
                                            {% if next_e.arena_set.count == 0 %}
                                                <a href="{% url 'generate_next_round' round.pk %}"
                                                   class=" mr-auto ml-auto mb-2">
                                                    <button class="btn login_btn" type="submit">
                                                        Generuj następną rundę
                                                    </button>
                                                </a>
                                            {% endif %}
                                        {% endwith %}
                                    {% elif x.round_number == tournament.round_set.count and x.finished_table  == x.total_table and x.total_table != 0%}
                                        <a href="{% url 'finish_tournaments' tournament.pk %}"
                                           class=" mr-auto ml-auto mb-2">
                                            <button class="btn login_btn" type="submit">
                                                Zakończ turniej
                                            </button>
                                        </a>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </div>
                            {% for arena in round.arena_set.all  %}
                                {% if round.arena_set.count == 2 %}
                                    <div class="row">
                                        <div class="empty-arena"> </div>
                                    </div>
                                {% endif %}
                                {% if round.arena_set.count == 1 %}
                                    <div class="row">
                                        <div class="empty-arena"> </div>
                                    </div>
                                    <div class="row">
                                        <div class="empty-arena"> </div>
                                    </div>
                                    <div class="row">
                                        <div class="empty-arena"> </div>
                                    </div>
                                {% endif %}
                                <div class="row">
                                        {% for x in arena.result_set.all  %}
                                    <div class="border arena col-12">
                                           {% if x.winner == arena.player1 %}
                                               <div class="row winner border-bottom">
                                                    <i class="fas fa-trophy mt-auto mb-auto"></i>
                                                   <div class="mt-auto mb-auto ml-2">{{ arena.player1 }}</div>
                                               </div>
                                               <div class="row losser">
                                                   <i class="fas fa-times mt-auto mb-auto"></i>
                                                   <div class="mt-auto mb-auto ml-2">{{ arena.player2 }}</div>
                                               </div>
                                           {% elif x.winner == arena.player2 %}
                                           <div class="row losser border-bottom">
                                                <i class="fas fa-times mt-auto mb-auto"></i>
                                               <div class="mt-auto mb-auto ml-2">{{ arena.player1 }}</div>
                                           </div>
                                           <div class="row winner">
                                                <i class="fas fa-trophy mt-auto mb-auto"></i>
                                               <div class="mt-auto mb-auto ml-2">{{ arena.player2 }}</div>
                                           </div>
                                           {% endif %}
                                    </div>
                                        {% endfor %}
                                </div>
                                {% if arena.result_set.count == 0 %}
                                <div class="row">
                                    <div class="border arena col-12">
                                        <div class="row no_result border-bottom">
                                            <div class="col-12">
                                                {{ arena.player1 }}
                                            </div>
                                        </div>
                                        <div class="row no_result">
                                            <div class="col-9">
                                                {{ arena.player2 }}
                                            </div>
                                            <div class="float-end col-3 p-0">
                                                <a href="{% url 'enter_result' arena.pk %}">
                                            <button class="btn result_btn" type="submit">
                                                <i class="fas fa-edit mr-2"> </i>
                                            </button>
                                            </a>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                                {% if round.arena_set.count == 4 %}
                                    <div class="row">
                                        <div class="empty-arena"> </div>
                                    </div>
                                {% endif %}
                                {% if round.arena_set.count == 2 %}
                                    <div class="row">
                                        <div class="empty-arena"> </div>
                                    </div>
                                    <div class="row">
                                        <div class="empty-arena"> </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/app/tournaments/update.html
{% extends 'app/scheleton.html' %}

{% block content %}
    <div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="main-card mt-5">
				<div class="d-flex justify-content-center">
					<h3 id="form-title" class="mt-2">Edytuj turniej</h3>
				</div>
				<div class="d-flex justify-content-center form_container mb-4">

					<form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            {{ form.name.label_tag }}
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-trophy"></i></span>
                                </div>
                                {{ form.name }}
                            </div>
                            {{ form.start_date.label_tag }}
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                                </div>
                                {{ form.start_date }}
                            </div>
                            {{ form.max_players.label_tag }}
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-users"></i></span>
                                </div>
                                {{ form.max_players }}
                            </div>
                        </div>
                        <div class="col-6">
                            <label>Przypisz graczy:</label>
                            <ul class="list-group" id="player-list">
                                {% for p in form.players  %}
                                    <li class="list-group-item list-background">{{ p }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="d-flex justify-content-center mt-4 login_container">
                        <input class="btn login_btn" type="submit" value="Dodaj turniej">
                    </div>
					</form>
				</div>
			</div>
		</div>
	</div>

    	<script>
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nazwa';
		form_fields[3].placeholder='Max graczy';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>

{% endblock %}